package com.comuline.app.constants

val locations = mapOf(
    "AC" to "ANCOL",
    "AK" to "ANGKE",
    "BBN" to "BRAMBANAN",
    "BJD" to "BOJONGGEDE",
    "BKS" to "BEKASI",
    "BKST" to "BEKASITIMUR",
    "BOI" to "BOJONGINDAH",
    "BOO" to "BOGOR",
    "BPR" to "BATUCEPER",
    "BST" to "BANDARASOEKARNOHATTA",
    "BUA" to "BUARAN",
    "CBN" to "CIBINONG",
    "CC" to "CICAYUR",
    "CE" to "CEPER",
    "CIT" to "CIBITUNG",
    "CJT" to "CILEJIT",
    "CKI" to "CIKINI",
    "CKR" to "CIKARANG",
    "CKY" to "CIKOYA",
    "CLT" to "CILEBUT",
    "CSK" to "CISAUK",
    "CTA" to "CITAYAM",
    "CTR" to "CITERAS",
    "CUK" to "CAKUNG",
    "CW" to "CAWANG",
    "DAR" to "DARU",
    "DL" to "DELANGGU",
    "DP" to "DEPOK",
    "DPB" to "DEPOKBARU",
    "DRN" to "DURENKALIBATA",
    "DU" to "DURI",
    "GDD" to "GONDANGDIA",
    "GGL" to "GROGOL",
    "GST" to "GANGSENTIONG",
    "GW" to "GAWOK",
    "JAKK" to "JAKARTAKOTA",
    "JAY" to "JAYAKARTA",
    "JMU" to "JURANGMANGU",
    "JN" to "JENAR",
    "JNG" to "JATINEGARA",
    "JUA" to "JUANDA",
    "KAT" to "KARET",
    "KBY" to "KEBAYORAN",
    "KDS" to "KALIDERES",
    "KLD" to "KLENDER",
    "KLDB" to "KLENDERBARU",
    "KMO" to "KEMAYORAN",
    "KMT" to "KRAMAT",
    "KPB" to "KAMPUNGBANDAN",
    "KRI" to "KRANJI",
    "KT" to "KLATEN",
    "KTA" to "KUTOARJO",
    "LNA" to "LENTENGAGUNG",
    "LPN" to "LEMPUYANGAN",
    "MGB" to "MANGGABESAR",
    "MGW" to "MAGUWO",
    "MJ" to "MAJA",
    "MRI" to "MANGGARAI",
    "MTR" to "MATRAMAN",
    "NMO" to "NAMBO",
    "PDJ" to "PONDOKRANJI",
    "PI" to "PORIS",
    "PL" to "PALUR",
    "PLM" to "PALMERAH",
    "POC" to "PONDOKCINA",
    "POK" to "PONDOKJATI",
    "PRP" to "PARUNGPANJANG",
    "PSE" to "PASARSENEN"
)

// Function to get name by ID
fun getLocationNameById(id: String): String? {
    return locations[id]
}